title: WeList
description: Hotel Directory
baseurl: ""
url: "https://welist.top"

collections:
  b:
    output: true
    permalink: /b/:name/

defaults:
  - scope:
      path: ""
      type: "b"
    values:
      layout: hotel
